export const API_ENDPOINT = '/';

export const USER_LOGIN_START = "USER_LOGIN_START";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";

export const CREATE_USER_START = "CREATE_USER_START";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";

export const GET_USERS_START = "GET_USERS_START";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";

export const GET_USER_PROFILE_START = "GET_USER_PROFILE_START";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";

export const EDIT_FEEDBACK_START = "EDIT_FEEDBACK_START";
export const EDIT_FEEDBACK_SUCCESS = "EDIT_FEEDBACK_SUCCESS";

export const ADD_USER_TO_REVIEW_START = "ADD_USER_TO_REVIEW_START";
export const ADD_USER_TO_REVIEWS_SUCCESS = "ADD_USER_TO_REVIEWS_SUCCESS";

export const SET_SHOW_CREATE_MODAL = "SET_SHOW_CREATE_MODAL";

export const REGISTER_USER_START = "REGISTER_USER_START";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";

export const SUBMIT_FEEDBACK_START = "SUBMIT_FEEDBACK_START";
export const SUBMIT_FEEDBACK_SUCCESS = "SUBMIT_FEEDBACK_SUCCESS";
